In [ ]:
import pandas as pd
import numpy as np

In [ ]:
test1 = [0.67,0,0.33,1]
test2 = ['Doctor','Data Scientist','Carpenter','Doctor']
test3 = ['Bengali','Hindi','Hindi','Bhojpuri']
test4 = [1,2,3,4]
name  = ['ram','balram','bharat','kishan']
df    = pd.DataFrame(columns = ['Name','Income','Profession','Mother Tongue','Native Place'])
df['Name']               = name
df['Income']             = test1
df['Profession']         = test2
df['Mother Tongue']      = test3
df['Native Place']       = test4
df

Name  Income      Profession Mother Tongue  Native Place
0     ram    0.67          Doctor       Bengali             1
1  balram    0.00  Data Scientist         Hindi             2
2  bharat    0.33       Carpenter         Hindi             3
3  kishan    1.00          Doctor      Bhojpuri             4

# Step 1:- Dissimilarity of nominal attribute -Profession

In [ ]:
nominal_column = 'Profession'
test1 = df[nominal_column].values
print('----------------------------------------------------------------------------------------------------------')
print('We have the following list of nominal attributes')
print(df[nominal_column].values)
print('\n')
test1       = df[nominal_column].values
dis_sim     = np.ones((len(test1),len(test1)))
dis_sim     = np.ones((len(test1),len(test1)))
for i in range(len(test1)):
  for j in range(len(test1)):
    if i<j:
      if test1[i]==test1[j]:
        dis_sim[i][j] = 0
        dis_sim[j][i] = 0

dis_sim_profession = dis_sim.copy()
print('----------------------------------------------------------------------------------------------------------')
print('The dissimilarity matrix attained where 0 refers to similarity and 1 refers to dissimilarity is given as ')
dissimilarity_nominal = pd.DataFrame(dis_sim,columns = [f'object_{i+1}' for i in range(len(test1))], index = [f'object_{i+1}' for i in range(len(test1))])
display(dissimilarity_nominal)


----------------------------------------------------------------------------------------------------------
We have the following list of nominal attributes
['Doctor' 'Data Scientist' 'Carpenter' 'Doctor']


----------------------------------------------------------------------------------------------------------
The dissimilarity matrix attained where 0 refers to similarity and 1 refers to dissimilarity is given as 


object_1  object_2  object_3  object_4
object_1       1.0       1.0       1.0       0.0
object_2       1.0       1.0       1.0       1.0
object_3       1.0       1.0       1.0       1.0
object_4       0.0       1.0       1.0       1.0

## Step2:- Dissimilarity calculation for nominal attribute - Mother Tongue

In [ ]:
nominal_column = 'Mother Tongue'
test1 = df[nominal_column].values
print('----------------------------------------------------------------------------------------------------------')
print('We have the following list of nominal attributes')
print(df[nominal_column].values)
print('\n')
test1       = df[nominal_column].values
dis_sim     = np.ones((len(test1),len(test1)))
dis_sim     = np.ones((len(test1),len(test1)))
for i in range(len(test1)):
  for j in range(len(test1)):
    if i<j:
      if test1[i]==test1[j]:
        dis_sim[i][j] = 0
        dis_sim[j][i] = 0

dis_sim_mother_tongue = dis_sim.copy()
print('----------------------------------------------------------------------------------------------------------')
print('The dissimilarity matrix attained where 0 refers to similarity and 1 refers to dissimilarity is given as ')
dissimilarity_nominal = pd.DataFrame(dis_sim,columns = [f'object_{i+1}' for i in range(len(test1))], index = [f'object_{i+1}' for i in range(len(test1))])
display(dissimilarity_nominal)


----------------------------------------------------------------------------------------------------------
We have the following list of nominal attributes
['Bengali' 'Hindi' 'Hindi' 'Bhojpuri']


----------------------------------------------------------------------------------------------------------
The dissimilarity matrix attained where 0 refers to similarity and 1 refers to dissimilarity is given as 


object_1  object_2  object_3  object_4
object_1       1.0       1.0       1.0       1.0
object_2       1.0       1.0       0.0       1.0
object_3       1.0       0.0       1.0       1.0
object_4       1.0       1.0       1.0       1.0

# Step 3: Dissimilarity based on ordinal attribute native place

In [ ]:
ordinal_column = 'Native Place'
test2      = df[ordinal_column].values
print('--------------------------------------------------------------------------------------------------------------------------------------------------------')
label_encode_ordinal = {4:4,3:3,2:2,1:1}

############# update anything above this line ######################

print('Step1')
print(f'The dictionary to be used for label encoding is {label_encode_ordinal}')
print('\n')

test2_enc            = [label_encode_ordinal[i] for i in test2]
print(f'The label encoded value for {test2} will be {test2_enc}')
print('\n')


print('--------------------------------------------------------------------------------------------------------------------------------------------------------')
print('Step 2')
print('We find the distinct number of values in encoded list ie., M')
M                    = len(set(test2_enc))
print(f'The value of M is {M}')
print('--------------------------------------------------------------------------------------------------------------------------------------------------------')

print('Step3')
ordinal_list_norm    = np.float_(np.array([(val-1)/(M-1) for val in test2_enc]))
print(f'The ordinal list {test2} which was label encoded to be {test2_enc} is now normalized using the formula mentioned to get {ordinal_list_norm} \n')
print('--------------------------------------------------------------------------------------------------------------------------------------------------------')

print('Step4')
dissimilarity_ordinal          = np.zeros((len(ordinal_list_norm),(len(ordinal_list_norm))))
for i in range(dissimilarity_ordinal.shape[0]):
  for j in range(dissimilarity_ordinal.shape[1]):
    dissimilarity_ordinal[i][j] = np.sqrt((ordinal_list_norm[i]-ordinal_list_norm[j])**2)
print('We calculated the distance between successive points to get the distance matrix as ')
display(pd.DataFrame(dissimilarity_ordinal,columns = test2,index=test2))

--------------------------------------------------------------------------------------------------------------------------------------------------------
Step1
The dictionary to be used for label encoding is {4: 4, 3: 3, 2: 2, 1: 1}


The label encoded value for [1 2 3 4] will be [1, 2, 3, 4]


--------------------------------------------------------------------------------------------------------------------------------------------------------
Step 2
We find the distinct number of values in encoded list ie., M
The value of M is 4
--------------------------------------------------------------------------------------------------------------------------------------------------------
Step3
The ordinal list [1 2 3 4] which was label encoded to be [1, 2, 3, 4] is now normalized using the formula mentioned to get [0.         0.33333333 0.66666667 1.        ] 

--------------------------------------------------------------------------------------------------------------------------------------

1         2         3         4
1  0.000000  0.333333  0.666667  1.000000
2  0.333333  0.000000  0.333333  0.666667
3  0.666667  0.333333  0.000000  0.333333
4  1.000000  0.666667  0.333333  0.000000

## Step4: Finding dissimilarity based on numerical attribute Income

In [ ]:
num_column = 'Income'
test3      = df[num_column].values
max        = 1
min        = 0

############ Update everything above this line ###########

norm_test3 = [(val-min)/(max-min) for val in test3]
print(norm_test3)
print('--------------------------------------------------------------------------------------------------------------------------------------------------------')

dissimilarity_numerical          = np.zeros((len(norm_test3),(len(norm_test3))))
for i in range(dissimilarity_numerical.shape[0]):
  for j in range(dissimilarity_numerical.shape[1]):
    dissimilarity_numerical[i][j] = np.sqrt((norm_test3[i]-norm_test3[j])**2)
print('We calculated the distance between successive points to get the distance matrix as ')
display(pd.DataFrame(dissimilarity_numerical,columns = test3,index=test3))

[0.67, 0.0, 0.33, 1.0]
--------------------------------------------------------------------------------------------------------------------------------------------------------
We calculated the distance between successive points to get the distance matrix as 


0.67  0.00  0.33  1.00
0.67  0.00  0.67  0.34  0.33
0.00  0.67  0.00  0.33  1.00
0.33  0.34  0.33  0.00  0.67
1.00  0.33  1.00  0.67  0.00

## Finding overall dissimilarity

In [ ]:
print('----------------------------------------------------------------------')
print('We have similarity matrix corresponding to nominal attribute - Profession')
display(dis_sim_profession)
print('\n')

print('----------------------------------------------------------------------')
print('We have similarity matrix corresponding to ordinal attribute - Mother Tongue')
display(dis_sim_mother_tongue)
print('\n')

print('----------------------------------------------------------------------')
print('We have similarity matrix corresponding to numerical attribute - Income')
display(dissimilarity_numerical)
print('\n')

print('----------------------------------------------------------------------')
print('We have similarity matrix corresponding to ordinal attribute -Native Place')
display(dissimilarity_ordinal)
print('\n')

----------------------------------------------------------------------
We have similarity matrix corresponding to nominal attribute - Profession


array([[1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 1.]])



----------------------------------------------------------------------
We have similarity matrix corresponding to ordinal attribute - Mother Tongue


array([[1., 1., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 1., 1.],
       [1., 1., 1., 1.]])



----------------------------------------------------------------------
We have similarity matrix corresponding to numerical attribute - Income


array([[0.  , 0.67, 0.34, 0.33],
       [0.67, 0.  , 0.33, 1.  ],
       [0.34, 0.33, 0.  , 0.67],
       [0.33, 1.  , 0.67, 0.  ]])



----------------------------------------------------------------------
We have similarity matrix corresponding to ordinal attribute -Native Place


array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [0.33333333, 0.        , 0.33333333, 0.66666667],
       [0.66666667, 0.33333333, 0.        , 0.33333333],
       [1.        , 0.66666667, 0.33333333, 0.        ]])

In [ ]:
total_sim = dissimilarity_numerical+dissimilarity_ordinal+dis_sim_profession+dis_sim_mother_tongue
print('Overall similarity matrix for attributes of mixed type is -')

findf = pd.DataFrame(total_sim/4,columns = df['Name'].values,index = df['Name'].values)
display(findf)
print('--------------------------------------------------------------------------------------------------------')

Overall similarity matrix for attributes of mixed type is -


ram    balram    bharat    kishan
ram     0.500000  0.750833  0.751667  0.582500
balram  0.750833  0.500000  0.415833  0.916667
bharat  0.751667  0.415833  0.500000  0.750833
kishan  0.582500  0.916667  0.750833  0.500000

--------------------------------------------------------------------------------------------------------


In [ ]:
print(f'The most similar - Balram and Bharat (similarity of 0.416)')
print(f'The most dissimilar - Balram and Kishan (similarity of 0.92)')

The most similar - Balram and Bharat (similarity of 0.416)
The most dissimilar - Balram and Kishan (similarity of 0.92)


In [ ]:
df

Name  Income      Profession Mother Tongue  Native Place
0     ram    0.67          Doctor       Bengali             1
1  balram    0.00  Data Scientist         Hindi             2
2  bharat    0.33       Carpenter         Hindi             3
3  kishan    1.00          Doctor      Bhojpuri             4

# Cosine Similirality

## The formula for calculating the cosine similarity is : 
```
Cos(x, y) = x . y / ||x|| * ||y||
```


In [2]:
import pandas as pd
import numpy as np
from scipy import stats

A=np.array([2,7,1,4])
B=np.array([3,8,1,4])
C=np.array([6,56,1,16])

cos_sim_1=np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
print (f"Cosine Similarity between A and B:{cos_sim_1}")
print (f"Cosine Distance between A and B:{1-cos_sim_1}")


cos_sim_2=np.dot(B,C)/(np.linalg.norm(B)*np.linalg.norm(C))
print (f"Cosine Similarity between B and C:{cos_sim_2}")
print (f"Cosine Distance between B and C:{1-cos_sim_2}")

cos_sim_3=np.dot(A,C)/(np.linalg.norm(A)*np.linalg.norm(C))
print (f"Cosine Similarity between A and C:{cos_sim_3}")
print (f"Cosine Distance between A and C:{1-cos_sim_3}")

print("Cosine Similarity is ", max(cos_sim_1,cos_sim_2,cos_sim_3))

Cosine Similarity between A and B:0.995306445590965
Cosine Distance between A and B:0.004693554409034961
Cosine Similarity between B and C:0.9558495142872933
Cosine Distance between B and C:0.044150485712706744
Cosine Similarity between A and C:0.9572824128565306
Cosine Distance between A and C:0.042717587143469404
Cosine is  0.995306445590965
